### ISSUE TITLE
Implement `domain_process_range` without storing the handle in `std::unique_ptr`

### ISSUE THREAD

**Issue by AntoineFroger** [NVIDIA/NVTX#29]
We should avoid relying on dynamic memory allocation when possible.  I don't think there is a strong reason for storing the range handle into a unique pointer.

Instead, we could:
1. Add a boolean member variable in the `domain_process_range` class.  It determines whether the range should be emitted or not
2. Create a move constructor for the `domain_process_range` class:

```
domain_process_range(domain_process_range&& other) noexcept
{
#ifndef NVTX_DISABLE
  handle = other.handle;
  generate = other.generate;
  other.generate = false;
#endif
}
```

**Comment by jrhemstad** [comment]
>  I don't think there is a strong reason for storing the range handle into a unique pointer.

Yeah, it was just a convenient way to make a rule of 0 object non-copyable and moveable. 

@jcohen-nvidia informed me that a `nvtxRangeId_t` will never be returned with a value of 0. So instead of an extra bool member, we can just use `0` as a sentinel for the "moved from" state.
