### ISSUE TITLE
Failed to build nvtx

### ISSUE THREAD

**Issue by juulie** [NVIDIA/NVTX#52]
Im getting a "Cannot open include file: 'nvtx3/nvToolsExt.h',

This is on windows, ive tried the suggestions in #43 but that doesnt seem to work. Ive tried defining C_INCLUDE in the windows path variables but that doesnt seem to help either.

Any ideas?

**Comment by shwina** [comment]
Hi @juulie - the environment variable you should set should be `C_INCLUDE_PATH`, and it should be set to the directory containing the `nvtx3` directory. Could you confirm what the value of `C_INCLUDE_PATH` is?

**Comment by juulie** [comment]
I had it set to my installation of gpu computing toolkit `C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v11.2\include` which does contain the nvtx3, and nvtx3/nvToolsExt.h

**Comment by juulie** [comment]
I managed to install it by copying the NVTX3 folder to the virtual environment include folder
