### ISSUE TITLE
how can i get nvToolsExt64_1.dll and nvToolsExt64_1.lib

### ISSUE THREAD

**Issue by pww1971** [NVIDIA/NVTX#70]
CMake Error at C:/Program Files/CMake/share/cmake-3.23/Modules/FindPackageHandleStandardArgs.cmake:230 (message):
  Could NOT find NvToolExt (missing: NvToolExt_LIBRARIES)

**Comment by EMEliasMi8859** [comment]
Hello 
You can install the older version of Cuda like 11.8 and copy the nvToolsExt from it past it in you current cuda which might be cuda 12.1 or later problem solved!!!

**Comment by evanramos-nvidia** [comment]
NVTXv3 is a header-only library that does not require these files, which were only needed for earlier versions. Make sure you are including `#include <nvtx3/nvToolsExt.h>`.

**Comment by evanramos-nvidia** [comment]
Please reopen this issue if it is not resolved for you.
