### ISSUE TITLE
Seeking for some explanations on the meaning of terminology in nvtx.h and nvToolsExtPayload.h

### ISSUE THREAD

**Issue by ZhiyiHu1999** [NVIDIA/NVTX#95]
Hello! I want to ask for some explanations on the meaning of these two teminology: "schema" and "payload". I feel confused about what they mean when reading the annotations of nvtx.h and nvToolsExtPayload.h. Thanks a lot!

**Comment by evanramos-nvidia** [comment]
`nvToolsExtPayload.h` is still in development. Documentation will be published alongside its formal release.
